// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run over a DIRECT (non-pooled) connection. Falls back to
    // DATABASE_URL for local setups that only define one.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
